// Personal repertoire — songs the guitarist knows how to play and sing
const SONGLIST = [
  { artist: 'Bee Gees', title: 'How Deep Is Your Love' },
  { artist: 'Fugees', title: 'Killing Me Softly' },
  { artist: 'Игорь Саруханов', title: 'Скрип Колеса (Скрипка-Лиса)' },
  { artist: 'Филипп Киркоров', title: 'Снег' },
  { artist: 'Moby', title: 'Natural Blues' },
  { artist: 'Ария', title: 'Потерянный Рай' },
  { artist: 'Уматурман', title: 'Объясни Мне' },
  { artist: 'Дмитрий Маликов', title: 'До Завтра' },
  { artist: 'Серьга', title: 'Страна Чудес' },
  { artist: 'Чайф', title: 'Вольный Ветер' },
  { artist: 'Моральный Кодекс', title: 'Где Ты' },
  { artist: 'Ария', title: 'Осколок Льда' },
  { artist: 'Мумий Тролль', title: 'Дельфины' },
  { artist: 'Алла Пугачева', title: 'Озеро Надежды' },
  { artist: 'Виагра', title: 'Бриллианты' },
  { artist: 'Монатик', title: 'Сильно' },
  { artist: 'Браво', title: 'Старый Отель' },
  { artist: 'The Offspring', title: 'Self Esteem' },
  { artist: 'Владимир Пресняков', title: 'Стюардесса По Имени Жанна' },
  { artist: 'Мумий Тролль', title: 'Делай Меня Точно' },
  { artist: 'Мумий Тролль', title: 'Кот Кота' },
  { artist: 'Мумий Тролль', title: 'Утекай' },
  { artist: 'Игорь Корнелюк', title: 'Билет На Балет' },
  { artist: 'Наутилус Помпилиус', title: 'Крылья' },
  { artist: 'Машина Времени', title: 'Пока Горит Свеча' },
  { artist: 'Чайф', title: 'Белая Ворона' },
  { artist: 'Король и Шут', title: 'Кукла Колдуна' },
  { artist: 'Уматурман', title: 'Проститься' },
  { artist: 'Браво', title: 'Московский Бит' },
  { artist: 'Мурат Насыров', title: 'Утиные Истории' },
  { artist: 'Сплин', title: 'Жертва Талого Льда' },
  { artist: 'Самоцветы', title: 'Не Надо Печалиться' },
  { artist: 'Руки Вверх', title: 'Лишь О Тебе Мечтая' },
  { artist: 'Любовь Успенская', title: 'Кабриолет' },
  { artist: 'Руки Вверх', title: 'Он Тебя Целует' },
  { artist: 'Григорий Лепс', title: 'Рюмка Водки На Столе' },
  { artist: 'Мурат Насыров', title: 'Кто-то Простит' },
  { artist: 'Zoloto', title: 'Непроизошло' },
  { artist: 'Manizha', title: 'Сейчас Дважды Не Случится' },
  { artist: 'Татьяна Буланова', title: 'Ясный Мой Свет' },
  { artist: 'Валерия', title: 'Таю' },
  { artist: 'Александр Серов', title: 'Я Люблю Тебя До Слез' },
  { artist: 'Алена Апина', title: 'Бухгалтер' },
  { artist: 'Анжелика Варум', title: 'Художник Что Рисует Дождь' },
  { artist: 'Ирина Аллегрова', title: 'Младший Лейтенант' },
  { artist: 'Алена Швец', title: 'Нас Не Догонят (Кавер Тату)' },
  { artist: 'Уматурман', title: 'Серега Говорит' },
  { artist: 'Маша и Медведи', title: 'Рейкьявик' },
  { artist: 'Кристина Орбакайте', title: 'Без Тебя' },
  { artist: 'Morgenshtern', title: 'Пустой Вокзал' },
  { artist: 'Morgenshtern', title: 'Повод' },
  { artist: 'Morgenshtern', title: 'Последняя Любовь' },
  { artist: 'Morgenshtern', title: 'Антидепрессанты' },
  { artist: 'Блестящие', title: 'Где же Ты Где' },
  { artist: 'Алена Свиридова', title: 'Розовый Фламинго' },
  { artist: 'Бумбокс', title: 'Хоттабыч' },
  { artist: 'Филипп Киркоров', title: 'Я Эту Жизнь Тебе Отдам' },
  { artist: 'Cream Soda & Хлеб', title: 'Плачу На Техно' },
  { artist: 'Агата Кристи', title: 'Вечная Любовь' },
  { artist: 'Тату', title: 'Мальчик-Гей' },
  { artist: 'Винтаж', title: 'Плохая Девочка' },
  { artist: 'Ирина Аллегрова', title: 'Незаконченный Роман' },
  { artist: 'Игорь Николаев', title: 'Пять Причин' },
  { artist: 'Алла Пугачева', title: 'Айсберг' },
  { artist: '4 Non Blondes', title: "What's Up" },
  { artist: 'Кар-Мэн', title: 'Чио-Чио-Сан' },
  { artist: 'Евгений Белоусов', title: 'Девчонка-Девчоночка' },
  { artist: 'Ялла', title: 'Последняя Поэма' },
  { artist: 'Анжелика Варум', title: 'Ля-Ля-Фа' },
  { artist: 'Чиж', title: 'Сен Симилья' },
  { artist: 'Алла Пугачева', title: 'Паромщик' },
  { artist: 'Валентина Толкунова', title: 'Я Не Могу Иначе' },
  { artist: 'Сплин', title: 'Нервное Сердце' },
  { artist: 'Воскресение', title: 'Кто Виноват' },
  { artist: 'Coldplay', title: 'A Sky Full Of Stars' },
  { artist: 'Кино и Мультфильмы', title: 'Снежинка (К/Ф «Чародей»)' },
  { artist: 'Beatles', title: 'Come Together' },
  { artist: 'Меладзе Валерий', title: 'Я Не Могу Без Тебя' },
  { artist: 'Black', title: 'Wonderful Life' },
  { artist: 'Свинцовый Туман', title: 'Я Знаю Придет Тот День' },
  { artist: 'Владимир Кузьмин', title: 'Надо Же' },
  { artist: 'Марсель', title: 'Сколько Бы' },
  { artist: 'Олег Анофриев', title: 'Есть Только Миг' },
  { artist: 'Самоцветы', title: 'Все Что в Жизни Есть У Меня' },
  { artist: 'Александр Градский', title: 'Как Молоды Мы Были' },
  { artist: 'Ha-Ha', title: 'Шляпа' },
  { artist: 'Animal Джаз', title: 'Реквием' },
  { artist: 'Максим Леонидов', title: 'Проплывая Над Городом' },
  { artist: 'Игорь Корнелюк', title: 'Дожди' },
  { artist: 'Максим Леонидов', title: 'Позывные Весны' },
  { artist: 'Григорий Гладков', title: 'Песня О Картинах' },
  { artist: 'Queen', title: 'Love Of My Life' },
  { artist: 'Quest Pistols', title: 'Ты Так Красива' },
  { artist: 'Анна Герман', title: 'Надежда' },
  { artist: 'Юлия Савичева', title: 'Прости За Любовь' },
  { artist: 'Яна', title: 'Одинокий Голубь' },
  { artist: 'Серега', title: 'Возле Дома Твоего' },
  { artist: 'Паскаль', title: 'Шелковое Сердце' },
  { artist: 'Винтаж', title: 'Ева' },
  { artist: 'Тату', title: '30 Минут' },
  { artist: 'Юлия Савичева', title: 'Привет' },
  { artist: 'Виктор Салтыков', title: 'Белая Ночь' },
  { artist: 'Полина Гагарина', title: 'Спектакль Окончен' },
  { artist: 'Григорий Лепс', title: 'Я Тебе Не Верю' },
  { artist: 'Brainstorm', title: 'Ты Не Один' },
  { artist: 'Total', title: 'Бьет По Глазам' },
  { artist: 'Черниковская Хата', title: 'Спектакль Окончен' },
  { artist: 'Черниковская Хата', title: 'Белая Ночь' },
  { artist: 'Игорь Николаев', title: 'Такси' },
  { artist: 'Алла Пугачева', title: 'Любовь Похожая На Сон' },
  { artist: 'Мумий Тролль', title: 'Такие Девчонки' },
  { artist: 'Roxette', title: 'Spending My Time' },
  { artist: 'The Hatters', title: 'Просто Проваливай' },
  { artist: 'Найк Борзов', title: 'Загадка' },
  { artist: 'Ляпис Трубецкой', title: '12 Обезьян' },
  { artist: 'Братья Грим', title: 'Аэроплан' },
  { artist: 'Город 312', title: 'Обернись' },
  { artist: 'Ярослав Евдокимов', title: 'Фантазер' },
  { artist: 'Adele', title: 'Make You Feel My Love' },
  { artist: 'Золотое Кольцо', title: 'Течет Ручей' },
  { artist: 'Маша и Медведи', title: 'Любочка' },
  { artist: 'Земфира', title: 'Почему' },
  { artist: 'Михаил Круг', title: 'Фраер' },
  { artist: 'Ляпис Трубецкой', title: 'Шут' },
  { artist: 'Brutto', title: 'Мяч' },
  { artist: 'The Calling', title: 'Wherever You Will Go' },
  { artist: 'Hoobastank', title: 'The Reason' },
  { artist: 'Король и Шут', title: 'Отец и Маски' },
  { artist: 'Король и Шут', title: 'Леший Обиделся' },
  { artist: 'Король и Шут', title: 'Внезапная Голова' },
  { artist: 'Король и Шут', title: 'Верная Жена' },
  { artist: 'Артемьев Павел', title: 'Понимаешь' },
  { artist: 'Hi-Fi', title: 'Беспризорник' },
  { artist: 'Демо', title: 'Солнышко' },
  { artist: 'Alphaville', title: 'Forever Young' },
  { artist: 'Меладзе Валерий', title: 'Девушка Из Высшего Общества' },
  { artist: 'Иван Дорн', title: 'Стыцамен' },
  { artist: 'Кино и Мультфильмы', title: 'Баллада Атоса' },
  { artist: 'Премьер-Министр', title: 'Восточная' },
  { artist: 'Ляпис Трубецкой', title: 'Евпатория' },
  { artist: 'Эдуард Хиль', title: 'Ходит Песенка По Кругу' },
  { artist: 'Руки Вверх', title: 'Алешка' },
  { artist: 'Ласковый Май', title: 'Розовый Вечер' },
  { artist: 'Татьяна Буланова', title: 'Не Плачь' },
  { artist: 'Мачете', title: 'Не Расставайтесь' },
  { artist: 'Abba', title: 'Gimme Gimme Gimme' },
  { artist: 'Земфира', title: 'Дыши' },
  { artist: 'Elvis Presley', title: "Can't Help Falling In Love" },
  { artist: 'Morgenshtern', title: 'Красный Флаг' },
  { artist: 'Король и Шут', title: 'Марионетки' },
  { artist: 'Nirvana', title: 'The Man Who Sold The World' },
  { artist: 'Awolnation', title: 'Seven Sticks Of Dynamite' },
  { artist: 'Blink 182', title: 'I Miss You' },
  { artist: 'Город 312', title: 'Девочка Которая Хотела Счастья' },
  { artist: 'Король и Шут', title: 'Лесник' },
  { artist: 'Базар', title: 'Дай Мне Любовь Свою' },
  { artist: 'Базар', title: 'До 30' },
  { artist: '25/17', title: 'Комната' },
  { artist: '5Nizza', title: 'Это Тебе' },
  { artist: 'Kings Of Leon', title: 'Sex On Fire' },
  { artist: 'Мумий Тролль', title: 'Медведица' },
  { artist: 'Иванушки International', title: 'Где-то' },
  { artist: 'Корни', title: '25 Этаж' },
  { artist: 'Feduk', title: 'Хлопья Летят Наверх' },
  { artist: 'Михей и Джуманджи', title: 'Сука-Любовь' },
  { artist: 'Depeche Mode', title: 'Personal Jesus' },
  { artist: 'Ben E. King', title: 'Stand By Me' },
  { artist: 'Леонид Агутин', title: 'На Сиреневой Луне' },
  { artist: 'Меладзе Валерий', title: 'Красиво' },
  { artist: 'Zoloto', title: 'Танго' },
  { artist: 'Игорь Тальков', title: 'Летний Дождь' },
  { artist: 'Король и Шут', title: 'Медведь' },
  { artist: 'George Michael', title: 'Careless Whisper' },
  { artist: 'System Of A Down', title: 'Hypnotize' },
  { artist: 'System Of A Down', title: 'Spiders' },
  { artist: 'Bob Seger', title: 'Turn The Page' },
  { artist: 'Metallica', title: 'Unforgiven II' },
  { artist: 'Coldplay', title: 'Spark' },
  { artist: 'Smashing Pumpkins', title: '1979' },
  { artist: 'Nelly Furtado', title: 'Say It Right' },
  { artist: 'Тату', title: 'Я Сошла С Ума' },
  { artist: 'Филипп Киркоров', title: 'Единственная' },
  { artist: 'Любовь Успенская', title: 'Карусель' },
  { artist: 'Кино и Мультфильмы', title: "Don't Stop Believin'" },
  { artist: 'Кино и Мультфильмы', title: 'Я Шагаю По Москве' },
  { artist: 'Кино и Мультфильмы', title: 'Старый Клен' },
  { artist: 'Кино и Мультфильмы', title: 'Ты Меня На Рассвете Разбудишь' },
  { artist: 'Кино и Мультфильмы', title: 'Лесной Олень' },
  { artist: 'Кино и Мультфильмы', title: 'Дороги Любви (Гардемарины)' },
  { artist: 'Кино и Мультфильмы', title: 'Мы Поедем Мы Помчимся' },
  { artist: 'Кино и Мультфильмы', title: 'На Тихорецкую (К/Ф «Ирония судьбы»)' },
  { artist: 'Анжелика Варум', title: 'Городок' },
  { artist: 'Машина Времени', title: 'Однажды Мир Прогнется Под Нас' },
  { artist: 'Abba', title: 'Happy New Year' },
  { artist: 'Леонид Агутин', title: 'Февраль' },
  { artist: 'Корни', title: 'Плакала Береза' },
  { artist: 'Аукцыон', title: 'Дорога' },
  { artist: 'Александр Иванов', title: 'Ночь' },
  { artist: 'Мумий Тролль', title: 'Голод' },
  { artist: 'Мумий Тролль', title: 'Так Надо' },
  { artist: 'Depeche Mode', title: 'Never Let Me Down Again' },
  { artist: 'Xolidayboy', title: 'Океаны' },
  { artist: 'Depeche Mode', title: 'Enjoy The Silence' },
  { artist: 'Игорь Корнелюк', title: 'Город Которого Нет' },
  { artist: 'Александр Иванов', title: 'Я Постелю Тебе Под Ноги Небо' },
  { artist: 'Леонид Агутин', title: 'Не Уходи Далеко' },
  { artist: 'Алла Пугачева', title: 'Не Отрекаются Любя' },
  { artist: 'Дискотека Авария', title: 'Если Хочешь Остаться' },
  { artist: 'Леонид Агутин', title: 'Половина Сердца' },
  { artist: 'Anna Asti', title: 'Царица' },
  { artist: 'Леонид Агутин', title: 'Голос Высокой Травы' },
  { artist: 'Леонид Агутин', title: 'Остров' },
  { artist: 'Баста', title: 'Выпускной (Медлячок)' },
  { artist: 'Lady Gaga', title: 'Shallow' },
  { artist: 'Алексей Глызин', title: 'Зимний Сад' },
  { artist: 'Линда', title: 'Марихуана' },
  { artist: 'Abba', title: 'The Winner Takes It All' },
  { artist: 'Браво', title: 'Однажды' },
  { artist: 'Carla Bruni', title: 'The Winner Takes It All' },
  { artist: 'Сплин', title: 'Пой Мне Еще' },
  { artist: 'Мураками', title: 'Нулевой Километр' },
  { artist: 'Robbie Williams', title: 'Angels' },
  { artist: 'Женя Трофимов', title: 'Ночь' },
  { artist: 'Женя Трофимов', title: 'Самолеты' },
  { artist: 'Coldplay', title: 'The Scientist' },
  { artist: 'Мурат Насыров', title: 'Я Это Ты' },
  { artist: 'Hi-Fi', title: 'Не Дано' },
  { artist: 'Моральный Кодекс', title: 'Первый Снег' },
  { artist: 'Веселые Ребята', title: 'В Последний Раз' },
  { artist: 'Beatles', title: 'Hey Jude' },
  { artist: 'Bob Marley', title: 'Three Little Birds' },
  { artist: 'Radiohead', title: 'Fake Plastic Trees' },
  { artist: 'Radiohead', title: 'Creep' },
  { artist: 'Radiohead', title: 'Karma Police' },
  { artist: 'Булат Окуджава', title: 'Десятый Десантный Батальон' },
  { artist: 'Александр Розенбаум', title: 'Ай' },
  { artist: 'Владимир Кузьмин', title: 'Две Звезды' },
  { artist: 'Мачете', title: 'Между Висками' },
  { artist: 'Наутилус Помпилиус', title: 'Я Хочу Быть С Тобой' },
  { artist: 'Иван Дорн', title: 'Целовать Другого' },
  { artist: 'Сплин', title: 'Маяк' },
  { artist: 'Леонид Агутин', title: 'Летний Дождь' },
  { artist: 'Браво', title: 'Лучший Город Земли' },
  { artist: 'Sirotkin', title: 'Планы На Это Лето' },
  { artist: 'Женя Трофимов', title: 'Поезда' },
  { artist: 'Мумий Тролль', title: 'Забавы' },
  { artist: 'Линда', title: 'Мало Огня' },
  { artist: 'Моральный Кодекс', title: 'До Свиданья Мама' },
  { artist: 'Animal Джаз', title: 'Три Полоски' },
  { artist: 'Леонид Агутин', title: 'Оле Оле' },
  { artist: 'Сосо Павлиашвили', title: 'Небо На Ладони' },
  { artist: 'Сплин', title: 'Тебе Это Снится' },
  { artist: 'Сплин', title: 'Алкоголь' },
  { artist: 'Сплин', title: 'Приходи' },
  { artist: 'Сплин', title: 'Моя Любовь' },
  { artist: 'Владимир Маркин', title: 'Я Готов Целовать Песок' },
  { artist: 'Непара', title: 'Другая Причина' },
  { artist: 'Сплин', title: 'Выхода Нет' },
  { artist: 'The White Stripes', title: 'Seven Nation Army' },
  { artist: 'Кино', title: 'Видели Ночь' },
  { artist: 'Звери', title: 'Районы Кварталы' },
  { artist: 'Юрий Антонов', title: '20 Лет Спустя' },
  { artist: 'Михаил Боярский', title: 'Спасибо Родная' },
  { artist: 'Антон Токарев', title: 'Седьмой Лепесток (Hi-Fi Cover)' },
  { artist: 'Кино и Мультфильмы', title: 'Позвони Мне Позвони' },
  { artist: 'Лицей', title: 'Осень' },
  { artist: 'Владимир Кузьмин', title: 'Эй Красотка' },
  { artist: 'Леонтьев Валерий', title: 'Полет На Дельтаплане' },
  { artist: 'Земфира', title: 'Мачо' },
  { artist: 'Би-2', title: 'Зажигать' },
  { artist: 'Би-2', title: 'Скользкие Улицы (Иномарки)' },
  { artist: 'Би-2', title: 'Компромисс' },
  { artist: 'Сплин', title: 'Сиануквиль' },
  { artist: 'Сплин', title: 'Весь Этот Бред' },
  { artist: 'Сплин', title: 'Орбит Без Сахара' },
  { artist: 'Кино', title: 'Странная Сказка' },
  { artist: 'Кино', title: 'Бездельник #1' },
  { artist: 'Кино', title: 'Красно-Желтые Дни' },
  { artist: 'Звери', title: 'Просто Такая Сильная Любовь' },
  { artist: 'Найк Борзов', title: 'Маленькая Лошадка' },
  { artist: 'Nirvana', title: 'Rape Me' },
  { artist: 'Angus & Julia Stone', title: 'Big Jet Plane' },
  { artist: 'Shocking Blue', title: 'Venus' },
  { artist: 'Би-2', title: 'Моя Любовь' },
  { artist: 'ДДТ', title: 'Летели Облака' },
  { artist: 'Linkin Park', title: 'Numb' },
  { artist: 'Мумий Тролль', title: 'Владивосток 2000' },
  { artist: 'Найк Борзов', title: 'Летчик' },
  { artist: 'Найк Борзов', title: 'Мечтать' },
  { artist: 'Найк Борзов', title: 'Лошадка' },
  { artist: 'Гражданская Оборона', title: 'Про Дурачка' },
  { artist: 'Сплин', title: 'Остаемся Зимовать' },
  { artist: 'Сплин', title: 'Мы Сидели И Курили' },
  { artist: 'Мираж', title: 'Новый Герой' },
  { artist: 'Юрий Шатунов', title: 'Седая Ночь' },
  { artist: 'Doors', title: 'People Are Strange' },
  { artist: 'Иванушки International', title: 'Колечко' },
  { artist: 'Хадн Дадн', title: 'Мы Сегодня Дома' },
  { artist: 'Beatles', title: 'While My Guitar Gently Weeps' },
  { artist: 'Chris Isaak', title: 'Wicked Game' },
  { artist: 'Сергей Никитин', title: 'Майдан' },
  { artist: 'Staind', title: 'Outside' },
  { artist: 'Земфира', title: 'Если Бы' },
  { artist: 'Шура', title: 'Ты Не Верь Слезам' },
  { artist: 'Амега', title: 'Лететь' },
  { artist: 'Браво', title: 'Это За Окном Рассвет' },
  { artist: 'Браво', title: 'Вася' },
  { artist: 'Браво', title: 'Дорога в Облака' },
  { artist: 'Народная', title: 'Полюшко-Поле' },
  { artist: 'System Of A Down', title: 'Roulette' },
  { artist: 'Валентин Стрыкало', title: 'Бесполезно' },
  { artist: 'Земфира', title: 'Кофевино' },
  { artist: 'Земфира', title: 'Пальто' },
  { artist: 'Николай Носков', title: 'Это Здорово' },
  { artist: 'Zoloto', title: 'Pmml' },
  { artist: 'Zoloto', title: 'Стихнет Мотор' },
  { artist: 'Robbie Williams', title: 'Supreme' },
  { artist: 'Кирпичи', title: 'Плюю Я' },
  { artist: 'Земфира', title: 'Крым' },
  { artist: 'Adele', title: 'Someone Like You' },
  { artist: 'Coldplay', title: 'Viva La Vida' },
  { artist: 'System Of A Down', title: 'Lonely Day' },
  { artist: 'Coldplay', title: 'Yellow' },
  { artist: 'Muse', title: 'Time Is Running Out' },
  { artist: 'Папин Олимпос', title: 'Темно-Оранжевый Закат' },
  { artist: 'Светлана Владимирская', title: 'Мальчик Мой' },
  { artist: 'Танцы Минус', title: '10 Капель Дождя' },
  { artist: 'Imagine Dragons', title: 'Walking The Wire' },
  { artist: 'Imagine Dragons', title: 'Radioactive' },
  { artist: 'Nick Cave', title: 'Where The Wild Roses Grow' },
  { artist: 'Metallica', title: 'Whiskey In The Jar' },
  { artist: 'Metallica', title: 'Unforgiven' },
  { artist: 'Меладзе Валерий', title: 'Сэйра' },
  { artist: 'Андрей Губин', title: 'Ночь' },
  { artist: 'Zoloto', title: 'Останемся Здесь' },
  { artist: 'Танцы Минус', title: 'Половинка' },
  { artist: 'Eurythmics', title: 'Sweet Dreams' },
  { artist: 'Черниковская Хата', title: 'Ночное Рандеву' },
  { artist: 'Billie Eilish', title: 'Ocean Eyes' },
  { artist: 'Imagine Dragons', title: 'Demons' },
  { artist: 'The Weeknd', title: 'Blinding Lights' },
  { artist: 'Marilyn Manson', title: 'Sweet Dreams' },
  { artist: 'Enrique Iglesias', title: 'Hero' },
  { artist: 'Onerepublic', title: 'Apologize' },
  { artist: 'Lionel Richie', title: 'Hello' },
  { artist: 'Sting', title: 'Every Breath You Take' },
  { artist: 'Natalie Imbruglia', title: 'Torn' },
  { artist: 'The Verve', title: 'Bittersweet Symphony' },
  { artist: 'Louis Armstrong', title: 'What A Wonderful World' },
  { artist: 'Kings Of Leon', title: 'Use Somebody' },
  { artist: 'Sting', title: 'Englishman In New York' },
  { artist: 'Иван Дорн', title: 'Северное Сияние' },
  { artist: 'Foo Fighters', title: 'Everlong' },
  { artist: 'Adele', title: 'Hello' },
  { artist: 'Beatles', title: 'Oh Darling' },
  { artist: 'Кино и Мультфильмы', title: 'Мне Нравится (К/Ф «Ирония судьбы»)' },
  { artist: 'Кино и Мультфильмы', title: 'Как Жизнь Без Весны' },
  { artist: 'Кино и Мультфильмы', title: 'Погоня (К/Ф «Новые приключения»)' },
  { artist: 'The Moody Blues', title: 'Nights In White Satin' },
  { artist: 'Cake', title: 'I Will Survive' },
  { artist: 'Hozier', title: 'Take Me To Church' },
  { artist: 'Beyonce', title: 'Halo' },
  { artist: 'Foo Fighters', title: 'My Hero' },
  { artist: 'Pretenders', title: "I'll Stand By You" },
  { artist: 'Muse', title: 'New Born' },
  { artist: 'Muse', title: "Can't Take My Eyes Off You" },
  { artist: 'Johnny Cash', title: 'Hurt' },
  { artist: 'Incubus', title: 'Drive' },
  { artist: 'Zoloto', title: 'Прикоснись ко Мне' },
  { artist: 'Иван Дорн', title: 'Живописный Мост' },
  { artist: 'Britney Spears', title: 'Baby One More Time' },
  { artist: 'Моральный Кодекс', title: 'Ночной Каприз' },
  { artist: 'A-Ha', title: 'Minor Earth Major Sky' },
  { artist: 'A-Ha', title: 'Summer Moved On' },
  { artist: 'A-Ha', title: 'Crying In The Rain' },
  { artist: 'Reamonn', title: 'Supergirl' },
  { artist: 'Animals', title: 'The House Of The Rising Sun' },
  { artist: 'Кино', title: 'Это Не Любовь' },
  { artist: 'Наутилус Помпилиус', title: 'Кто Еще' },
  { artist: 'Total', title: 'Адреналин' },
  { artist: 'Иванушки International', title: 'Вселенная' },
  { artist: 'Lana Del Rey', title: 'Born To Die' },
  { artist: 'Найк Борзов', title: 'Ссора' },
  { artist: '5Nizza', title: 'Это Не Кино' },
  { artist: 'Gotye', title: 'Somebody That I Used To Know' },
  { artist: 'Savage Garden', title: 'To The Moon And Back' },
  { artist: 'Savage Garden', title: 'Truly Madly Deeply' },
  { artist: 'HIM', title: 'Gone With The Sin' },
  { artist: 'Red Hot Chili Peppers', title: 'Californication' },
  { artist: 'Red Hot Chili Peppers', title: 'By The Way' },
  { artist: 'Red Hot Chili Peppers', title: 'Under The Bridge' },
  { artist: 'Валентин Стрыкало', title: 'Наше Лето' },
  { artist: 'Connells', title: '74-75' },
  { artist: "Guns N' Roses", title: "Don't Cry" },
  { artist: 'Prince', title: 'Purple Rain' },
  { artist: 'Gnarls Barkley', title: 'Crazy' },
  { artist: 'Elton John', title: 'Your Song' },
  { artist: 'B. J. Thomas', title: 'Raindrops Keep Falling On My Head' },
  { artist: 'Police', title: 'Roxanne' },
  { artist: 'Монеточка', title: 'Нимфоманка' },
  { artist: 'Placebo', title: 'Meds' },
  { artist: 'Queen', title: 'The Show Must Go On' },
  { artist: 'Michael Jackson', title: 'Billie Jean' },
  { artist: 'Баста', title: 'Сансара' },
  { artist: 'Бумбокс', title: 'Вахтерам' },
  { artist: 'Звери', title: 'Дожди-Пистолеты' },
  { artist: 'Звери', title: 'Районы-Кварталы' },
  { artist: 'Найк Борзов', title: 'Бардак в Голове' },
  { artist: 'Iowa', title: 'Бьет Бит' },
  { artist: 'Гречка', title: 'Люби Меня Люби' },
  { artist: 'Руки Вверх', title: 'Крошка Моя' },
  { artist: 'Сплин', title: 'Феллини' },
  { artist: 'Michael Jackson', title: 'Give In To Me' },
  { artist: 'U2', title: 'One' },
  { artist: 'Nirvana', title: 'Something In The Way' },
  { artist: '5Nizza', title: 'Ты Такая' },
  { artist: '5Nizza', title: 'Весна' },
  { artist: 'Joy Division', title: 'Love Will Tear Us Apart' },
  { artist: 'Валентин Стрыкало', title: 'Ты Не Такая' },
  { artist: 'Goo Goo Dolls', title: 'Iris' },
  { artist: 'Sirotkin', title: 'Лисы-Волки' },
  { artist: 'Depeche Mode', title: 'Stripped' },
  { artist: 'Sirotkin', title: 'Голоса Имена и Ты' },
  { artist: 'Hi-Fi', title: 'Седьмой Лепесток' },
  { artist: 'Kiss', title: "I Was Made For Lovin' You" },
  { artist: 'Nirvana', title: 'Polly' },
  { artist: 'Nirvana', title: 'Come As You Are' },
  { artist: 'Скриптонит', title: 'Это Любовь' },
  { artist: 'Земфира', title: 'Жить в Твоей Голове' },
  { artist: 'Кино и Мультфильмы', title: 'Ветер Перемен' },
  { artist: 'A-Ha', title: 'Take On Me' },
  { artist: 'Bob Dylan', title: "Knockin' On Heaven's Door" },
  { artist: 'Zoloto', title: 'Ты Не Верь Слезам' },
  { artist: 'Nirvana', title: 'Heart Shaped Box' },
  { artist: 'Backstreet Boys', title: 'I Want It That Way' },
  { artist: 'Nickelback', title: 'How You Remind Me' },
  { artist: 'Beatles', title: 'Norwegian Wood' },
  { artist: 'Nirvana', title: 'Man Who Sold The World' },
  { artist: 'The Righteous Brothers', title: 'Unchained Melody' },
  { artist: 'Britney Spears', title: 'Toxic' },
  { artist: 'The Cure', title: "Friday I'm In Love" },
  { artist: 'Tenacious D', title: 'Fuck Her Gently' },
  { artist: 'Bill Withers', title: "Ain't No Sunshine" },
  { artist: 'U2', title: 'With Or Without You' },
  { artist: 'Gary Jules', title: 'Mad World' },
  { artist: 'Алена Швец', title: 'Скейтер' },
  { artist: 'Maneskin', title: "Beggin'" },
  { artist: 'Maneskin', title: '2504' },
  { artist: 'Отпетые Мошенники', title: 'Люби Меня Люби' },
  { artist: 'Виагра', title: 'Притяженья Больше Нет' },
  { artist: 'Jeff Buckley', title: 'Hallelujah' },
  { artist: 'Меладзе Валерий', title: 'Океан И Три Реки' },
  { artist: 'Земфира', title: 'Блюз' },
  { artist: 'Мачете', title: 'Нежность' },
  { artist: 'Би-2', title: 'Молитва' },
  { artist: 'Меладзе Валерий', title: 'Самба Белого Мотылька' },
  { artist: 'Bon Jovi', title: 'Always' },
  { artist: 'Алла Пугачева', title: 'Позови Меня С Собой' },
  { artist: 'Лев Лещенко', title: 'Прощай' },
  { artist: 'Мираж', title: 'Музыка Нас Связала' },
  { artist: 'Максим', title: 'Знаешь Ли Ты' },
  { artist: 'Иванушки International', title: 'Тучи' },
  { artist: 'Михаил Боярский', title: 'Зеленоглазое Такси' },
  { artist: "Sinead O'Connor", title: 'Nothing Compares To You' },
  { artist: 'Гражданская Оборона', title: 'Отряд Не Заметил Потери Бойца' },
  { artist: 'Леонид Агутин', title: 'Ты Вернешься Опять' },
  { artist: 'Синяя Птица', title: 'Там Где Клен Шумит' },
  { artist: 'Justin Timberlake', title: 'Cry Me A River' },
  { artist: 'Animal Джаз', title: 'Дыши' },
  { artist: 'Scorpions', title: 'Still Loving You' },
  { artist: 'А-Студио', title: 'Еще Люблю' },
  { artist: 'Алсу', title: 'Весна' },
  { artist: 'Банда', title: 'Плачут Небеса' },
  { artist: 'Александр Серов', title: 'Как Быть' },
  { artist: 'Леонтьев Валерий', title: 'Маргарита' },
  { artist: 'Леонтьев Валерий', title: 'Исчезли Солнечные Дни' },
  { artist: 'Кино и Мультфильмы', title: 'Всегда Быть Рядом' },
  { artist: 'Сергей Никитин', title: 'Переведи Меня Через Майдан' },
  { artist: 'Иванушки International', title: 'Кукла' },
  { artist: 'Гости Из Будущего', title: 'Беги От Меня' },
  { artist: 'Владимир Пресняков', title: 'Замок Из Дождя' },
  { artist: 'Леонид Агутин', title: 'Аэропорты' },
  { artist: 'Кар-Мэн', title: 'Лондон Гудбай' },
  { artist: 'Madonna', title: 'Like A Prayer' },
  { artist: 'А-Студио', title: 'Нелюбимая' },
  { artist: 'Юлия Савичева', title: 'Если в Сердце Живет Любовь' },
  { artist: 'Ирина Дубцова', title: 'О Нем' },
  { artist: 'Валерия', title: 'Самолет' },
  { artist: 'Меладзе Валерий', title: 'Как Ты Красива Сегодня' },
  { artist: 'Рок-Острова', title: 'Ничего Не Говори' },
  { artist: 'Фабрика', title: 'Про Любовь' },
  { artist: 'Иванушки International', title: 'Снегири' },
  { artist: 'Александр Иванов', title: 'Тоже Является Частью Вселенной' },
  { artist: 'Корни', title: 'Я Теряю Корни' },
  { artist: 'Анжелика Варум', title: 'Зимняя Вишня' },
  { artist: 'Алсу', title: 'Иногда' },
  { artist: 'Кино и Мультфильмы', title: 'Этот Мир Придуман Не Мной' },
  { artist: 'Кино и Мультфильмы', title: 'Помоги Мне' },
  { artist: 'Boney M', title: 'Rasputin' },
];

export default SONGLIST;
